services:
    mongodb-service:
        image: mongo:7.0-rc-jammy
        container_name: mongodb-1
        environment:
            MONGO_INITDB_ROOT_USERNAME: MONGO_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: MONGO_PASSWORD
        ports:
            - 27018:27017
        volumes:
            - ./database_laptop_store:/data/db

    # Remove mongodb-express-service service if you don't want build
    mongodb-express-service:
        image: mongo-express
        container_name: mongo-express-1
        restart: unless-stopped
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: CONFIG_MONGODB_ADMINUSERNAME
            ME_CONFIG_MONGODB_ADMINPASSWORD: CONFIG_MONGODB_ADMINPASSWORD
            ME_CONFIG_MONGODB_SERVER: mongodb-service
            ME_CONFIG_BASICAUTH_USERNAME: CONFIG_BASICAUTH_USERNAME
            ME_CONFIG_BASICAUTH_PASSWORD: CONFIG_BASICAUTH_PASSWORD
        depends_on:
            - mongodb-service

volumes:
    mongodb_data_container:
# docker compose -f ./docker-compose-db.yml -p database up -d
